### ISSUE TITLE
Add table with images of the traffic scenarios

### ISSUE THREAD

**Issue by martinbaerwolff** [OpenTrafficCam/OTDocs#65]
https://github.com/OpenTrafficCam/OTDocs/blob/5dc1702d910c41254f483193c014801d4c36e385/docs/OTAnalytics/Accuracy/counts.md#L8

Please use the names from the table below :)

**Comment by frunika** [comment]
I think it's done, isn't it?

**Comment by arminkollascheck** [comment]
yes
