### ISSUE TITLE
Make hyperlink text more distinguishable from standard text.

### ISSUE THREAD

**Issue by randy-seng** [OpenTrafficCam/OTDocs#68]
As of now it is really hard to tell the difference between hyperlink and normal static text

![find_the_hyperlink](https://user-images.githubusercontent.com/19281702/143494412-eba796c1-6b50-43da-8f43-ce8287f88f14.png)

## Question
Should we change the color? If so, which color should we change it to? @frunika  @martinbaerwolff 

## Instructions
[How to change the color in mkdocs](https://github.com/squidfunk/mkdocs-material/issues/1583)

**Comment by frunika** [comment]
Yeah you're right. We already had a discussion about it and didn't look further into it. Any suggestions for colors? I'll personally think a underline could be more visible and intuitive.

**Comment by frunika** [comment]
If you have any suggestions @randy-seng feel free to optimize ;)
