### ISSUE TITLE
Incorrect label in image showing the structure of OTValidate

### ISSUE THREAD

**Issue by martinbaerwolff** [OpenTrafficCam/OTDocs#80]
In the image showing the structure of OTValidate on https://opentrafficcam.org/OTLabels/validation/overview/#otvalidate to me it seems the green sheets on the right side have incorrect labels (2x "Track performance metrics", 1x "Detection performance  metrics")

Would this be correct?:
- "Detection perfomance metrics"
- "Tracking performance metrics"
- "Traffic perfomance metrics"

Furthermore it may be more precise to speak of "traffic counts" instead of just "traffic" or "counts"

**Comment by randy-seng** [comment]
Thank you  @martinbaerwolff. Yes, you are right! They have been labeled incorrectly.

I've also replaced "count" with "traffic counts"

Here is the corrected diagram:

![Screenshot 2022-01-13 at 16 53 44](https://user-images.githubusercontent.com/19281702/149364208-7a5b604c-6b83-459b-8d37-8f08af7fe7ad.png)

**Comment by martinbaerwolff** [comment]
Thanks for the correction! Maybe also 

- "Ground Truth Traffic Counts" instead of "Ground Truth Traffic" (Yellow element)
- "traffic counting" instead of "traffic analysis" (in OTValidate)
- "Traffic Counts Performance Metrics" instead of "Traffic Performance Metrics" (Green element)?

**Comment by randy-seng** [comment]
Understood! Just like this right?

![Screenshot 2022-01-13 at 21 48 37](https://user-images.githubusercontent.com/19281702/149406959-ed17f0f1-875f-44f5-853d-39ca8daa088f.png)

**Comment by martinbaerwolff** [comment]
Jep :) Thanks!
